"""empty message

Revision ID: 31fd96e67bef
Revises: 
Create Date: 2020-02-29 18:33:56.399948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fd96e67bef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('o_id', sa.Integer(), nullable=False),
    sa.Column('o_name', sa.String(), nullable=True),
    sa.Column('o_num', sa.Float(), nullable=True),
    sa.Column('o_bool', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('o_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objects')
    # ### end Alembic commands ###
